# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\project\jd_gui\gui\ui_file\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 645)
        MainWindow.setMinimumSize(QtCore.QSize(602, 645))
        MainWindow.setMaximumSize(QtCore.QSize(602, 645))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/alian/Desktop/download.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shopInfos = QtWidgets.QTableView(self.centralwidget)
        self.shopInfos.setGeometry(QtCore.QRect(20, 80, 551, 441))
        self.shopInfos.setObjectName("shopInfos")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 551, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.start_shop_id = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.start_shop_id.setObjectName("start_shop_id")
        self.horizontalLayout.addWidget(self.start_shop_id)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.end_shop_id = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.end_shop_id.setObjectName("end_shop_id")
        self.horizontalLayout.addWidget(self.end_shop_id)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 520, 301, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clear_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_2.addWidget(self.clear_button)
        self.export_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.export_button.setObjectName("export_button")
        self.horizontalLayout_2.addWidget(self.export_button)
        self.export_qcc_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.export_qcc_button.setObjectName("export_qcc_button")
        self.horizontalLayout_2.addWidget(self.export_qcc_button)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(440, 520, 131, 81))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_4.addWidget(self.search_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(19, 50, 551, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.shop_status = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.shop_status.setObjectName("shop_status")
        self.horizontalLayout_3.addWidget(self.shop_status)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.thread_count = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.thread_count.setObjectName("thread_count")
        self.horizontalLayout_3.addWidget(self.thread_count)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "京东店铺抓取"))
        self.label.setText(_translate("MainWindow", "店铺起始ID:"))
        self.label_2.setText(_translate("MainWindow", "店铺终止ID:"))
        self.clear_button.setText(_translate("MainWindow", "清空"))
        self.export_button.setText(_translate("MainWindow", "导出"))
        self.export_qcc_button.setText(_translate("MainWindow", "导出企查查"))
        self.search_button.setText(_translate("MainWindow", "开始查询"))
        self.label_3.setText(_translate("MainWindow", "状态："))
        self.label_4.setText(_translate("MainWindow", "线程数："))
